name: P-bde
favicon: null
layout_spectrum: 0.9663843801245093
typography_spectrum: 0.550651588710025
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.18580813892185688
  lightness: 0.39159566769376397
  saturation: 0.5083332841750234
  rhythmicContrast: 0.8470069183968008
purpose: []
